language: python
dist: xenial
sudo: true
services:
  - redis-server
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - "python setup.py develop"
  - "pip install -r requirements.txt"
  - "pip install pytest-cov"
  - "pip install coveralls"
script:
  - py.test --cov-config .coveragerc --cov=synergine2 ./tests/
after_success:
  - coveralls
